const predefinedTasks = [
    // Tâches ménagères
    "Do the laundry",
    "Clean the kitchen",
    "Vacuum the living room",
    "Take out the trash",
    "Organize the closet",
    "Dust the shelves",
    "Mop the floor",
    "Wash the windows",
    "Clean the bathroom",
    "Clean the fridge",
    "Disinfect high-touch surfaces",
    "Organize the pantry",
    "Wipe down kitchen counters",
    "Clean the oven",
    "Clean out the garage",
    "Cook dinner",

    // Tâches administratives
    "Pay the bills",
    "Schedule a doctor's appointment",
    "Renew car insurance",
    "Send an email to HR",
    "File the tax report",
    "Update personal documents",
    "Check the bank statement",
    "Review credit card statements",
    "File important paperwork",
    "Request a copy of the birth certificate",
    "Update passwords for security",
    "Check and renew subscriptions",
    
    // Tâches liées au travail
    "Prepare for the meeting",
    "Finish the project report",
    "Update the team on Slack",
    "Code review for the pull request",
    "Brainstorm new ideas for the project",
    "Attend the conference call",
    "Organize team-building event",
    "Prepare marketing presentation",
    "Check project deadlines",
    "Review project plan with the team",
    "Research industry trends",

    // Tâches personnelles
    "Go for a run",
    "Meditate for 10 minutes",
    "Call mom",
    "Read a book",
    "Plan a vacation",
    "Take a break and relax",
    "Practice a new skill",
    "Start a journal",
    "Plan weekly meals",
    "Learn a new language",
    "Take a yoga class",
    "Write in the diary",
    "Unwind with music",
    "Practice mindfulness",

    // Tâches d'achat
    "Buy groceries",
    "Pick up the dry cleaning",
    "Order pet food",
    "Buy birthday gift for John",
    "Restock office supplies",
    "Order a new phone charger",
    "Buy a new pair of shoes",
    "Pick up prescription from pharmacy",
    "Buy new towels",
    "Shop for winter clothes",
    "Order a new mattress",
    "Order a new laptop case",

    // Autres
    "Prepare presentation for Monday",
    "Fix the leaky faucet",
    "Water the plants",
    "Research a new hobby",
    "Watch a tutorial on React",
    "Prepare the garden for winter",
    "Clean the car",
    "Organize the files on the computer",
    "Back up important files",
    "Update the software on the devices",
    "Sort out old clothes to donate",
    "Create a home inventory list",
    "Take a walk in the park"
];
  
export default predefinedTasks;
